#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with
#+ a sleep of 2 sec in between each iteration.
#   Displays "I am invincible!!!" in between each iteration.

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
